# Namespace
kind: Namespace
apiVersion: v1
metadata:
  name: nigelpoulton
---
# Deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nigelpoulton-web
  namespace: nigelpoulton
  labels:
    app: nigelpoulton-web
spec:
  selector:
    matchLabels:
      app: nigelpoulton-web
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nigelpoulton-web
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: np-web
        image: gingergraham/getting-started-k8s:2.0
        imagePullPolicy: Always
        resources:
          # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 8080
--- 
# Service
# LoadBalancer service works with cloud K8s or on MicroK8s if MetalLB is enabled
# https://microk8s.io/docs/addon-metallb
kind: Service
apiVersion: v1
metadata:
  name: np-loadbalancer
  namespace: nigelpoulton
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: http-alternate
    protocol: TCP
    port: 81
    targetPort: 8080
  selector:
    app: nigelpoulton-web

# Nodeport service for internal only
# kind: Service
# apiVersion: v1
# metadata:
#   name: np-web-nodeport
#   namespace: nigelpoulton
# spec:
#   type: NodePort
#   ports:
#   - port: 80
#     targetPort: 8080
#     # nodePort: 30000
#     protocol: TCP
#   selector:
#     app: nigelpoulton-web
---
# Ingress

# Ingress service but I couldn't get this working on a bare metal deployment - switched to MetalLB and a LoadBalancer service
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nigelpoulton-web-ingress
#   namespace: nigelpoulton
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$1
#     kubernetes.io/ingress.class: merge
#     merge.ingress.kubernetes.io/config: ingress
# spec:
#   rules:
#     - host: nigelpoulton.wattsfamily.org.uk
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: np-web-nodeport
#                 port:
#                   number: 80
